# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'js/tests/*'
        - 'vendor/*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds. 10 minutes
        runs: 1
